# Form implementation generated from reading ui file 'E:\Personal Projects\___Pycharm___\Bo_bai_tap\Ex127\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 602)
        MainWindow.setStyleSheet("background-color: #1e1e1e;")

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 671, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("background-color: #2d2d2d; color: white; border: 1px solid #555;")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 440, 55, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: white;")

        button_style = (
            "QPushButton {"
            "    background-color: #007acc;"
            "    color: white;"
            "    font-size: 14px;"
            "    font-weight: bold;"
            "    border-radius: 10px;"
            "    padding: 10px;"
            "}"
            "QPushButton:hover {"
            "    background-color: #005f99;"
            "}"
        )

        self.pushButton = QtWidgets.QPushButton("Refresh Data", parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 530, 120, 41))
        self.pushButton.setStyleSheet(button_style)

        self.pushButton_2 = QtWidgets.QPushButton("Sort By Price", parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 470, 120, 41))
        self.pushButton_2.setStyleSheet(button_style)

        self.pushButton_3 = QtWidgets.QPushButton("Reduce by Symbol", parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 470, 140, 41))
        self.pushButton_3.setStyleSheet(button_style)

        self.pushButton_4 = QtWidgets.QPushButton("USD Column", parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 470, 120, 41))
        self.pushButton_4.setStyleSheet(button_style)

        self.pushButton_5 = QtWidgets.QPushButton("Add New Row", parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 530, 120, 41))
        self.pushButton_5.setStyleSheet(button_style)

        self.pushButton_6 = QtWidgets.QPushButton("Statistics", parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 530, 120, 41))
        self.pushButton_6.setStyleSheet(button_style)

        self.pushButton_7 = QtWidgets.QPushButton("Delete", parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(380, 530, 120, 41))
        self.pushButton_7.setStyleSheet(button_style)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Manager"))